# Generated by Django 4.0.3 on 2022-03-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cart_id_alter_customer_id_alter_orderplaced_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('P', '2BHK'), ('F', '3BHK'), ('PE', 'Land'), ('E', 'Villa')], max_length=2),
        ),
    ]
